name: Build and store image
on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      image-tag:
        required: false
        type: string
        default: latest
      mix-environment:
        required: false
        type: string
        default: prod
      npm-script:
        required: false
        type: string
        default: build
    secrets:
      KEENMATE_REGISTRY_USERNAME:
        required: true
      KEENMATE_REGISTRY_PASSWORD:
        required: true
jobs:
  build:
    name: Build and deploy image
    runs-on: self-hosted
    env:
      MIX_ENV: ${{ inputs.mix-environment }}
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        registry: registry.km8.es
        username: ${{ secrets.KEENMATE_REGISTRY_USERNAME }}
        password: ${{ secrets.KEENMATE_REGISTRY_PASSWORD }}
    - uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          registry.km8.es/${{ inputs.image-name }}:${{ inputs.image-tag }}
        build-args: |
          NPM_TOKEN=${{ secrets.KEENMATE_NPM_TOKEN }}
          NPM_SCRIPT=${{ inputs.npm-script }}
          MIX_ENV=${{ inputs.mix-environment }}