name: Deploy Docker image
on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      image-tag:
        required: false
        type: string
        default: latest

      # Path of docker build context
      docker-build-context:
        required: false
        type: string
        default: .
      # Relative to context
      dockerfile-name:
        required: false
        type: string
        default: Dockerfile
      deployment-host:
        required: true
        type: string
      deployment-dir:
        required: true
        type: string
      mix-environment:
        required: false
        type: string
        default: prod
      npm-script:
        required: false
        type: string
        default: build
    secrets:
      KEENMATE_REGISTRY_USERNAME:
        required: true
      KEENMATE_REGISTRY_PASSWORD:
        required: true
      KEENMATE_NPM_TOKEN:
        required: false
      NUGET_USERNAME:
        required: false
      NUGET_PASSWORD:
        required: false
      BUILDER_SSH_USERNAME:
        required: true
      BUILDER_SSH_KEY:
        required: true
      BUILDER_SSH_PASSPHRASE:
        required: true
jobs:
  build:
    uses: ./.github/workflows/build-store-image.yml
    with:
      image-name: ${{ inputs.image-name }}
      image-tag: ${{ inputs.image-tag }}
      docker-build-context: ${{ inputs.docker-build-context }}
      dockerfile-name: ${{ inputs.dockerfile-name }}
      mix-environment: ${{ inputs.mix-environment }}
      npm-script: ${{ inputs.npm-script }}
    secrets:
      KEENMATE_REGISTRY_USERNAME: ${{ secrets.KEENMATE_REGISTRY_USERNAME }}
      KEENMATE_REGISTRY_PASSWORD: ${{ secrets.KEENMATE_REGISTRY_PASSWORD }}
      KEENMATE_NPM_TOKEN: ${{ secrets.KEENMATE_NPM_TOKEN }}
      NUGET_USERNAME: ${{ secrets.NUGET_USERNAME }}
      NUGET_PASSWORD: ${{ secrets.NUGET_PASSWORD }}

  deploy:
    name: Deploy image
    needs: build
    runs-on: self-hosted
    steps:
    - uses: appleboy/ssh-action@v1
      with:
        host: ${{ inputs.deployment-host }}
        port: 22
        username: ${{ secrets.BUILDER_SSH_USERNAME }}
        key: ${{ secrets.BUILDER_SSH_KEY }}
        passphrase: ${{ secrets.BUILDER_SSH_PASSPHRASE }}
        script: |
          cd /srv/docker/${{ inputs.deployment-dir }}
          docker compose down
          docker compose pull
          docker compose up -d
