name: Deploy Docker image
on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      image-tag:
        required: true
        type: string
      deployment-host:
        required: true
        type: string
      deployment-dir:
        required: true
        type: string
      mix-environment:
        required: false
        type: string
        default: prod
    secrets:
      KEENMATE_REGISTRY_USERNAME:
        required: true
      KEENMATE_REGISTRY_PASSWORD:
        required: true
      BUILDER_SSH_USERNAME:
        required: true
      BUILDER_SSH_KEY:
        required: true
      BUILDER_SSH_PASSPHRASE:
        required: true
      KEENMATE_NPM_TOKEN:
        required: false
jobs:
  build:
    name: Build release
    runs-on: self-hosted
    env:
      MIX_ENV: ${{ inputs.mix-environment }}
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        registry: registry.km8.es
        username: ${{ secrets.KEENMATE_REGISTRY_USERNAME }}
        password: ${{ secrets.KEENMATE_REGISTRY_PASSWORD }}
    - uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          registry.km8.es/${{ inputs.image-name }}:${{ inputs.image-tag }}
        build-args: |
          NPM_TOKEN=${{ secrets.KEENMATE_NPM_TOKEN }}
          MIX_ENV=${{ inputs.mix-environment }}
    - uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ inputs.deployment-host }}
        port: 22
        username: ${{ secrets.BUILDER_SSH_USERNAME }}
        key: ${{ secrets.BUILDER_SSH_KEY }}
        passphrase: ${{ secrets.BUILDER_SSH_PASSPHRASE }}
        script: |
          cd /srv/docker/${{ inputs.deployment-dir }}
          docker-compose down
          docker-compose pull
          docker-compose up -d